server:
  port: 3344

spring:
  application:
    name:  cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jiuweile998/Test-springcloud-config.git #https://github.com/jiuweile998/Test-springcloud-config.git #GitHub上面的git仓库名字
          force-pull: true #设置强行pull拉取
          ####搜索目录
          search-paths:
            - Test-springcloud-config
      ####读取分支
      #label: main

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

