server:
  port: 2003

spring:
  application:
    name: Seata-AccountService2003
  cloud:
    alibaba:
      seata:
        tx-service-group: test_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
